param(
    [switch]$DryRun
)

$ErrorActionPreference = 'SilentlyContinue'

function Get-HomeDirectory {
    if (-not [string]::IsNullOrWhiteSpace($HOME)) { return $HOME }
    return [Environment]::GetFolderPath('UserProfile')
}

function Get-CopilotRoot {
    Join-Path (Get-HomeDirectory) '.copilot'
}

function Get-PluginRoot {
    Split-Path -Parent $PSScriptRoot
}

function Get-UserStateRoot {
    Join-Path (Get-CopilotRoot) 'oh-my-copilot'
}

function Test-LegacyLearningsFile {
    param(
        [string]$Path
    )

    if (-not (Test-Path $Path)) { return $false }

    $sample = Get-Content -Path $Path -TotalCount 20 -ErrorAction SilentlyContinue
    if (-not $sample) { return $false }

    $preview = $sample -join "`n"
    return (
        $preview -match 'Auto-generated by sessionEnd hook' -or
        $preview -match 'Auto-committed:' -or
        $preview -match '\[timestamp\].*MANUAL:' -or
        $preview -match '^\[\d{4}-\d{2}-\d{2}'
    )
}

function Ensure-OmcState {
    $pluginRoot  = Get-PluginRoot
    $stateRoot   = Get-UserStateRoot
    $dbPath      = Join-Path $stateRoot 'omc-memory.db'
    $learnPath   = Join-Path $stateRoot 'LEARNINGS.md'
    $legacyDb    = Join-Path $pluginRoot 'omc-memory.db'
    $legacyLearn = Join-Path $pluginRoot 'LEARNINGS.md'

    if (-not (Test-Path $stateRoot)) {
        [void](New-Item -ItemType Directory -Path $stateRoot -Force)
    }

    if (-not (Test-Path $dbPath)) {
        if (Test-Path $legacyDb) {
            Copy-Item -Path $legacyDb -Destination $dbPath -Force
        } else {
            $initScript = Join-Path $PSScriptRoot 'init-memory.ps1'
            if (Test-Path $initScript) {
                [void](& $initScript -DbPath $dbPath 2>$null)
            }
        }
    }

    if (-not (Test-Path $learnPath)) {
        if (Test-LegacyLearningsFile -Path $legacyLearn) {
            Copy-Item -Path $legacyLearn -Destination $learnPath -Force
        } else {
            [void](New-Item -ItemType File -Path $learnPath -Force)
        }
    }

    [PSCustomObject]@{
        Root      = $stateRoot
        DbPath    = $dbPath
        LearnPath = $learnPath
    }
}

function Get-ChangedPathsFromStatus {
    param(
        [string[]]$StatusLines
    )

    $paths = @()
    foreach ($line in $StatusLines) {
        if ([string]::IsNullOrWhiteSpace($line)) { continue }

        $path = if ($line.Length -ge 4) { $line.Substring(3).Trim() } else { $line.Trim() }
        if ($path -match ' -> ') {
            $path = ($path -split ' -> ')[-1].Trim()
        }

        if (-not [string]::IsNullOrWhiteSpace($path)) {
            $paths += ($path -replace '\\', '/')
        }
    }

    return $paths
}

function Test-IsSharedSourcePath {
    param(
        [string]$Path
    )

    if ([string]::IsNullOrWhiteSpace($Path)) { return $false }

    return (
        $Path -match '^agents/' -or
        $Path -match '^scripts/' -or
        $Path -match '^hooks\.json$' -or
        $Path -match '^plugin\.json$' -or
        $Path -match '^LEARNINGS\.md$' -or
        $Path -match '^README\.md$' -or
        $Path -match '^local/README\.md$' -or
        $Path -match '^\.gitignore$'
    )
}

function Test-IsReadmeSyncGuardPath {
    param(
        [string]$Path
    )

    if ([string]::IsNullOrWhiteSpace($Path)) { return $false }

    return (
        $Path -match '^agents/' -or
        $Path -match '^scripts/' -or
        $Path -match '^hooks\.json$' -or
        $Path -match '^plugin\.json$' -or
        $Path -match '^local/README\.md$' -or
        $Path -match '^\.gitignore$'
    )
}

$copilotRoot        = Get-CopilotRoot
$pluginRoot         = Get-PluginRoot
$logPath            = Join-Path $copilotRoot 'session.log'
$consolidateScript  = Join-Path $PSScriptRoot 'consolidate.ps1'
$timestamp          = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
$currentDirectory   = (Get-Location).Path
$git                = Get-Command git -ErrorAction SilentlyContinue

if (-not $DryRun) {
    $statePaths = Ensure-OmcState
    $learnPath  = $statePaths.LearnPath
} else {
    $learnPath = Join-Path (Get-UserStateRoot) 'LEARNINGS.md'
}

if (-not $DryRun) {
    if (-not (Test-Path $copilotRoot)) {
        [void](New-Item -ItemType Directory -Path $copilotRoot -Force)
    }

    Add-Content -Path $logPath -Value "[$timestamp] SESSION_END cwd=$currentDirectory"
}

Push-Location $pluginRoot
try {
    if (-not $git) {
        Write-Host "[omc] Git not available, skipping auto-learn commit"
    } else {
        $status       = @(& $git.Source status --porcelain --untracked-files=all 2>$null)
        $changedPaths = @(Get-ChangedPathsFromStatus -StatusLines $status | Select-Object -Unique)
        $sharedPaths  = @($changedPaths | Where-Object { Test-IsSharedSourcePath $_ })
        $readmeSyncPaths = @($changedPaths | Where-Object { Test-IsReadmeSyncGuardPath $_ })
        $readmeChanged = $changedPaths -contains 'README.md'
        $ignoredPaths = @($changedPaths | Where-Object { -not (Test-IsSharedSourcePath $_) })

        if ($readmeSyncPaths.Count -gt 0 -and -not $readmeChanged) {
            throw "[omc] README sync required before session end: update README.md for $($readmeSyncPaths -join ', ')"
        }

        if ($sharedPaths.Count -gt 0) {
            if ($DryRun) {
                Write-Host "[omc] DryRun: would git add shared paths: $($sharedPaths -join ', ')"
                Write-Host "[omc] DryRun: would git commit -m `"auto-learn: $timestamp`" --no-verify"
                Write-Host "[omc] DryRun: would git push origin main"
                Write-Host "[omc] DryRun: would append auto-commit note to user-local LEARNINGS.md"
            } else {
                $gitAddArgs = @('add', '--') + $sharedPaths
                [void](& $git.Source @gitAddArgs 2>$null)
                $stagedPaths = @(& $git.Source diff --cached --name-only -- 2>$null)

                if ($stagedPaths.Count -eq 0) {
                    Write-Host "[omc] Shared source changes detected, but nothing was staged"
                } else {
                    $sharedSummary = @($stagedPaths | ForEach-Object { $_ -replace '\\', '/' })
                    $sharedSummary = @($sharedSummary | Select-Object -Unique)

                    $message = "auto-learn: $timestamp"
                    [void](& $git.Source commit -m $message --no-verify 2>$null)
                    if ($LASTEXITCODE -eq 0) {
                        [void](& $git.Source push origin main 2>$null)
                        Add-Content -Path $learnPath -Value "[$timestamp] Auto-committed shared changes: $($sharedSummary -join ', ')"
                        Write-Host "[omc] Self-improved: committed shared source changes"
                    } else {
                        Write-Host "[omc] Shared source changes detected, but commit failed"
                    }
                }
            }
        } elseif ($ignoredPaths.Count -gt 0) {
            Write-Host "[omc] Ignoring personal/runtime changes for auto-commit: $($ignoredPaths -join ', ')"
        } else {
            Write-Host "[omc] No shared source changes to commit"
        }
    }

    if ($DryRun) {
        Write-Host "[omc] DryRun: would run $consolidateScript"
    } elseif (Test-Path $consolidateScript) {
        & $consolidateScript 2>$null
    }
} finally {
    Pop-Location
}
