param(
    [switch]$DryRun
)

$ErrorActionPreference = 'Continue'

function Get-HomeDirectory {
    if (-not [string]::IsNullOrWhiteSpace($HOME)) { return $HOME }
    return [Environment]::GetFolderPath('UserProfile')
}

function Get-CopilotRoot {
    Join-Path (Get-HomeDirectory) '.copilot'
}

function Get-PluginRoot {
    Split-Path -Parent $PSScriptRoot
}

function Get-UserStateRoot {
    Join-Path (Get-CopilotRoot) 'oh-my-copilot'
}

function Test-IsWSL {
    # WSL sets WSL_DISTRO_NAME; fallback to /proc/version for older WSL1
    [bool]($env:WSL_DISTRO_NAME -or (Test-Path '/proc/version' -ErrorAction SilentlyContinue))
}

function Test-IsWindows {
    # Exclude WSL: WSL reports OS=Windows_NT but is a Linux environment
    (-not (Test-IsWSL)) -and ($env:OS -eq 'Windows_NT')
}

function Resolve-Sqlite3Path {
    $command = Get-Command sqlite3 -ErrorAction SilentlyContinue
    if ($command -and $command.Source) { return $command.Source }

    $command = Get-Command sqlite3.exe -ErrorAction SilentlyContinue
    if ($command -and $command.Source) { return $command.Source }

    if (Test-IsWindows) {
        $localAppData = $env:LOCALAPPDATA
        if (-not [string]::IsNullOrWhiteSpace($localAppData)) {
            $wingetPath = Join-Path $localAppData 'Microsoft\WinGet\Packages\SQLite.SQLite_Microsoft.Winget.Source_8wekyb3d8bbwe\sqlite3.exe'
            if (Test-Path $wingetPath) { return $wingetPath }
        }
    }

    $pathEntries = New-Object System.Collections.ArrayList
    foreach ($pathValue in @($env:PATH, [Environment]::GetEnvironmentVariable('PATH', 'User'), [Environment]::GetEnvironmentVariable('PATH', 'Machine'))) {
        if ([string]::IsNullOrWhiteSpace($pathValue)) { continue }
        foreach ($entry in ($pathValue -split [IO.Path]::PathSeparator)) {
            if (-not [string]::IsNullOrWhiteSpace($entry) -and -not ($pathEntries -contains $entry)) {
                [void]$pathEntries.Add($entry)
            }
        }
    }

    foreach ($entry in $pathEntries) {
        foreach ($candidateName in @('sqlite3', 'sqlite3.exe')) {
            $candidate = Join-Path $entry $candidateName
            if (Test-Path $candidate) { return $candidate }
        }
    }

    return $null
}

function Test-LegacyLearningsFile {
    param(
        [string]$Path
    )

    if (-not (Test-Path $Path)) { return $false }

    $sample = Get-Content -Path $Path -TotalCount 20 -ErrorAction SilentlyContinue
    if (-not $sample) { return $false }

    $preview = $sample -join "`n"
    return (
        $preview -match 'Auto-generated by sessionEnd hook' -or
        $preview -match 'Auto-committed:' -or
        $preview -match '\[timestamp\].*MANUAL:' -or
        $preview -match '^\[\d{4}-\d{2}-\d{2}'
    )
}

function Ensure-OmcState {
    $pluginRoot  = Get-PluginRoot
    $stateRoot   = Get-UserStateRoot
    $dbPath      = Join-Path $stateRoot 'omc-memory.db'
    $learnPath   = Join-Path $stateRoot 'LEARNINGS.md'
    $legacyDb    = Join-Path $pluginRoot 'omc-memory.db'
    $legacyLearn = Join-Path $pluginRoot 'LEARNINGS.md'

    if (-not (Test-Path $stateRoot)) {
        [void](New-Item -ItemType Directory -Path $stateRoot -Force)
    }

    if (-not (Test-Path $dbPath)) {
        if (Test-Path $legacyDb) {
            Copy-Item -Path $legacyDb -Destination $dbPath -Force
        } else {
            $initScript = Join-Path $PSScriptRoot 'init-memory.ps1'
            if (Test-Path $initScript) {
                [void](& $initScript -DbPath $dbPath 2>$null)
            }
        }
    }

    if (-not (Test-Path $learnPath)) {
        if (Test-LegacyLearningsFile -Path $legacyLearn) {
            Copy-Item -Path $legacyLearn -Destination $learnPath -Force
        } else {
            [void](New-Item -ItemType File -Path $learnPath -Force)
        }
    }

    [PSCustomObject]@{
        Root      = $stateRoot
        DbPath    = $dbPath
        LearnPath = $learnPath
    }
}

function Get-ChangedPathsFromStatus {
    param(
        [string[]]$StatusLines
    )

    $paths = @()
    foreach ($line in $StatusLines) {
        if ([string]::IsNullOrWhiteSpace($line)) { continue }

        $path = if ($line.Length -ge 4) { $line.Substring(3).Trim() } else { $line.Trim() }
        if ($path -match ' -> ') {
            $path = ($path -split ' -> ')[-1].Trim()
        }

        if (-not [string]::IsNullOrWhiteSpace($path)) {
            $paths += ($path -replace '\\', '/')
        }
    }

    return $paths
}

function Test-IsSharedSourcePath {
    param(
        [string]$Path
    )

    if ([string]::IsNullOrWhiteSpace($Path)) { return $false }

    return (
        $Path -match '^agents/' -or
        $Path -match '^scripts/' -or
        $Path -match '^hooks\.json$' -or
        $Path -match '^plugin\.json$' -or
        $Path -match '^LEARNINGS\.md$' -or
        $Path -match '^README\.md$' -or
        $Path -match '^local/README\.md$' -or
        $Path -match '^\.gitignore$'
    )
}

function Test-IsReadmeSyncGuardPath {
    param(
        [string]$Path
    )

    if ([string]::IsNullOrWhiteSpace($Path)) { return $false }

    return (
        $Path -match '^agents/' -or
        $Path -match '^scripts/' -or
        $Path -match '^hooks\.json$' -or
        $Path -match '^plugin\.json$' -or
        $Path -match '^local/README\.md$' -or
        $Path -match '^\.gitignore$'
    )
}

function ConvertTo-SqliteLiteral {
    param(
        [AllowNull()]
        [string]$Value
    )

    if ($null -eq $Value) { return '' }
    return $Value -replace "'", "''"
}

function Get-ContentHash {
    param(
        [string]$Content
    )

    try {
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($Content)
        $hasher = [System.Security.Cryptography.SHA256]::Create()
        $hash = $hasher.ComputeHash($bytes)
        return ([System.BitConverter]::ToString($hash) -replace '-', '').ToLower()
    } catch {
        # Fallback: use simple string hash
        return ($Content.GetHashCode().ToString('X8') + $Content.Length)
    }
}

function Ensure-ProposalsFile {
    param(
        [string]$Path
    )

    if (-not (Test-Path $Path)) {
        [void](New-Item -ItemType File -Path $Path -Force)
        @() | ConvertTo-Json | Set-Content -Path $Path -Encoding UTF8
    }
}

function Add-Proposal {
    param(
        [string]$ProposalType,
        [string]$Description,
        [string]$FilePath,
        [string]$Priority = 'normal',
        [string]$SuggestedChange = ''
    )

    Ensure-ProposalsFile -Path $PROPOSALS_PATH
    
    # Content hash for deduplication
    $contentHash = Get-ContentHash -Content "$ProposalType`:$FilePath`:$SuggestedChange"
    
    # Load existing proposals and check for duplicates
    try {
        $proposals = Get-Content -Path $PROPOSALS_PATH -Raw | ConvertFrom-Json
        if ($null -eq $proposals) { $proposals = @() }
        elseif (-not ($proposals -is [array])) { $proposals = @($proposals) }
        
        $existing = $proposals | Where-Object { $_.contentHash -eq $contentHash } | Select-Object -First 1
        if ($existing) {
            Write-Error "[omc] Proposal already queued (dedup: $contentHash, id: $($existing.id))" -ErrorAction Continue
            return $true
        }
    } catch {
        # If JSON is malformed, we'll overwrite it
        $proposals = @()
    }
    
    # Generate unique ID
    $timestamp = Get-Date -Format 'yyyyMMddHHmmss'
    $proposalId = "$timestamp-$($contentHash.Substring(0, 8))"
    
    # Create proposal object
    $proposal = [PSCustomObject]@{
        id = $proposalId
        timestamp = (Get-Date -Format 'o')  # ISO 8601 format
        type = $ProposalType
        description = $Description
        filePath = $FilePath
        priority = $Priority
        suggestedChange = $SuggestedChange
        contentHash = $contentHash
        status = 'pending'
    }
    
    # Add to array and save
    $proposals += $proposal
    try {
        $proposals | ConvertTo-Json -Depth 10 | Set-Content -Path $PROPOSALS_PATH -Encoding UTF8
        Write-Error "[omc] Proposal queued ($ProposalType): $Description (id: $proposalId)" -ErrorAction Continue
        return $true
    } catch {
        Write-Error "[omc] Failed to write proposal to $PROPOSALS_PATH : $_" -ErrorAction Continue
        return $false
    }
}


function Ensure-ImprovementCandidatesTable {
    param(
        [string]$DbPath
    )

    $sqlite3 = Resolve-Sqlite3Path
    if (-not $sqlite3) {
        throw "[omc] sqlite3 is required to queue shared-source improvement proposals"
    }

    $initScript = Join-Path $PSScriptRoot 'init-memory.ps1'
    if (-not (Test-Path $DbPath) -and (Test-Path $initScript)) {
        [void](& $initScript -DbPath $DbPath 2>$null)
    }

    $schema = @"
CREATE TABLE IF NOT EXISTS improvement_candidates (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at        DATETIME DEFAULT CURRENT_TIMESTAMP,
    proposal_kind     TEXT    DEFAULT 'shared_source_change',
    plugin_root       TEXT    NOT NULL,
    git_remote_name   TEXT,
    git_remote_url    TEXT,
    git_branch        TEXT,
    head_commit       TEXT,
    changed_paths     TEXT    NOT NULL,
    status_snapshot   TEXT    NOT NULL
);
"@

    $schema | & $sqlite3 $DbPath | Out-Null
    if ($LASTEXITCODE -ne 0) {
        throw "[omc] Failed to ensure improvement_candidates table"
    }

    return $sqlite3
}

function Resolve-GitRemoteContext {
    param(
        [string]$GitExe
    )

    $remoteName = ''
    $upstreamRef = @(& $GitExe rev-parse --abbrev-ref --symbolic-full-name '@{upstream}' 2>$null)
    if ($upstreamRef.Count -gt 0 -and -not [string]::IsNullOrWhiteSpace($upstreamRef[0])) {
        $candidate = $upstreamRef[0].Trim()
        if ($candidate -match '/') {
            $remoteName = ($candidate -split '/')[0]
        }
    }

    if ([string]::IsNullOrWhiteSpace($remoteName)) {
        [void](& $GitExe remote get-url origin 2>$null)
        if ($LASTEXITCODE -eq 0) {
            $remoteName = 'origin'
        } else {
            $remoteName = (@(& $GitExe remote 2>$null) | Select-Object -First 1)
        }
    }

    $remoteUrl = ''
    if (-not [string]::IsNullOrWhiteSpace($remoteName)) {
        $remoteUrl = (@(& $GitExe remote get-url $remoteName 2>$null) | Select-Object -First 1)
    }

    [PSCustomObject]@{
        Name = $remoteName
        Url  = $remoteUrl
    }
}

function Add-ImprovementCandidate {
    param(
        [string]$DbPath,
        [string]$GitExe,
        [string]$PluginRoot,
        [string[]]$SharedPaths,
        [string[]]$StatusLines
    )

    $sqlite3 = Ensure-ImprovementCandidatesTable -DbPath $DbPath
    $remoteContext = Resolve-GitRemoteContext -GitExe $GitExe
    $branchName = (@(& $GitExe rev-parse --abbrev-ref HEAD 2>$null) | Select-Object -First 1)
    $headCommit = (@(& $GitExe rev-parse HEAD 2>$null) | Select-Object -First 1)
    $changedPathsSnapshot = ($SharedPaths | Select-Object -Unique) -join "`n"
    $statusSnapshot = $StatusLines -join "`n"

    $insert = @"
INSERT INTO improvement_candidates (
    proposal_kind,
    plugin_root,
    git_remote_name,
    git_remote_url,
    git_branch,
    head_commit,
    changed_paths,
    status_snapshot
) VALUES (
    'shared_source_change',
    '$(ConvertTo-SqliteLiteral $PluginRoot)',
    '$(ConvertTo-SqliteLiteral $remoteContext.Name)',
    '$(ConvertTo-SqliteLiteral $remoteContext.Url)',
    '$(ConvertTo-SqliteLiteral $branchName)',
    '$(ConvertTo-SqliteLiteral $headCommit)',
    '$(ConvertTo-SqliteLiteral $changedPathsSnapshot)',
    '$(ConvertTo-SqliteLiteral $statusSnapshot)'
);
"@

    $insert | & $sqlite3 $DbPath | Out-Null
    if ($LASTEXITCODE -ne 0) {
        throw "[omc] Failed to record shared-source improvement proposal"
    }

    # Also record in JSON proposals file for transparency (NEW)
    $proposalDesc = "shared-source changes detected: $($SharedPaths -join ', ') (branch: $branchName, remote: $($remoteContext.Name))"
    if (-not (Add-Proposal -ProposalType 'shared-source-change' -Description $proposalDesc -FilePath $PluginRoot -Priority 'normal' -SuggestedChange $changedPathsSnapshot)) {
        Write-Host "[omc] Warning: Failed to record proposal in JSON queue (continuing with SQLite record)" -ForegroundColor Yellow
    }
}


$copilotRoot        = Get-CopilotRoot
$pluginRoot         = Get-PluginRoot
$logPath            = Join-Path $copilotRoot 'session.log'
$consolidateScript  = Join-Path $PSScriptRoot 'consolidate.ps1'
$timestamp          = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
$currentDirectory   = (Get-Location).Path
$git                = Get-Command git -ErrorAction SilentlyContinue
$PROPOSALS_PATH     = Join-Path (Get-UserStateRoot) 'proposals.json'

try {
    if (-not $DryRun) {
        try {
            $statePaths = Ensure-OmcState
            $learnPath  = $statePaths.LearnPath
        } catch {
            [Console]::Error.WriteLine("[omc] ERROR: Failed to initialize state directories: $_")
            exit 1
        }
    } else {
        $learnPath = Join-Path (Get-UserStateRoot) 'LEARNINGS.md'
    }

    if (-not $DryRun) {
        try {
            if (-not (Test-Path $copilotRoot)) {
                [void](New-Item -ItemType Directory -Path $copilotRoot -Force)
            }
            Add-Content -Path $logPath -Value "[$timestamp] SESSION_END cwd=$currentDirectory"
        } catch {
            [Console]::Error.WriteLine("[omc] ERROR: Failed to write session log: $_")
        }
    }

    Push-Location $pluginRoot
    try {
        if (-not $git) {
            Write-Host "[omc] Git not available, skipping shared-source proposal queue"
        } else {
            $status       = @(& $git.Source status --porcelain --untracked-files=all 2>$null)
            $changedPaths = @(Get-ChangedPathsFromStatus -StatusLines $status | Select-Object -Unique)
            $sharedPaths  = @($changedPaths | Where-Object { Test-IsSharedSourcePath $_ })
            $readmeSyncPaths = @($changedPaths | Where-Object { Test-IsReadmeSyncGuardPath $_ })
            $readmeChanged = $changedPaths -contains 'README.md'
            $ignoredPaths = @($changedPaths | Where-Object { -not (Test-IsSharedSourcePath $_) })

            if ($readmeSyncPaths.Count -gt 0 -and -not $readmeChanged) {
                throw "[omc] README sync required before session end: update README.md for $($readmeSyncPaths -join ', ')"
            }

            if ($sharedPaths.Count -gt 0) {
                $sharedSummary = @($sharedPaths | Select-Object -Unique)

                if ($DryRun) {
                    Write-Host "[omc] DryRun: would queue shared-source improvement proposal for: $($sharedSummary -join ', ')"
                } else {
                    Add-ImprovementCandidate -DbPath $statePaths.DbPath -GitExe $git.Source -PluginRoot $pluginRoot -SharedPaths $sharedSummary -StatusLines $status
                    Write-Host "[omc] Queued shared-source improvement proposal in user-local memory for: $($sharedSummary -join ', ')"
                }
            } elseif ($ignoredPaths.Count -gt 0) {
                Write-Host "[omc] Ignoring personal/runtime changes for shared-source proposal queue: $($ignoredPaths -join ', ')"
            } else {
                Write-Host "[omc] No shared source changes to queue"
            }
        }

        if ($DryRun) {
            Write-Host "[omc] DryRun: would run $consolidateScript"
        } elseif (Test-Path $consolidateScript) {
            & $consolidateScript 2>$null
        }
    } finally {
        Pop-Location
    }
} catch {
    # powershell.exe -File does not reliably convert uncaught script errors into a failing process exit code.
    $message = if ($_.Exception -and -not [string]::IsNullOrWhiteSpace($_.Exception.Message)) {
        $_.Exception.Message
    } else {
        $_.ToString()
    }

    [Console]::Error.WriteLine($message)
    exit 1
}
